### ISSUE TITLE
(wip) 'Favorites' playlist not recognized

### ISSUE THREAD

**Issue by patrickkfkan** [TimeForANinja/node-ytpl#100]
Hello,

Me again ^_^

I found that ID of Favorite-type playlists start with 'FL' and so does not get recognized by ytpl. 

I'm not sure if all 'Favorites' playlists start with 'FL', though. I just came across this in [this channel](https://www.youtube.com/user/RusMusic/playlists).

To get playlist IDs starting with 'FL to load', I changed this line in `main.js`:

>const PLAYLIST_REGEX = exports.PLAYLIST_REGEX = /^(PL|UU|LL|RD)[a-zA-Z0-9-_]{16,41}$/;

to this:

>const PLAYLIST_REGEX = exports.PLAYLIST_REGEX = /^(FL|PL|UU|LL|RD)[a-zA-Z0-9-_]{16,41}$/;

ytpl is able to load the playlist afterwards.

-Patrick

**Comment by TimeForANinja** [comment]
🤔 i knew about `WL` for `Watch Later` but ignored them since they are always private

guess there's no reason to not support `FL`-Playlists
nice spotting, will add support & tests later today 👍🏻
