### ISSUE TITLE
I am getting an error with ytpl 

### ISSUE THREAD

**Issue by aditya-learns** [TimeForANinja/node-ytpl#101]
```
/*****************************************************************************************************
 * validateURL will be renamed to validateID to match with getPlaylistID in the next release of ytpl *
 *                   set `ytpl.do_warn_deprecate = false` to disable this message                    *
 *****************************************************************************************************/
/Users/adityagupta/Desktop/DashBot/node_modules/ytpl/lib/util.js:27
    title: exports.removeHtml(importantTxt.match(PLAYLIST_NAME_REGEXP)[1]),
                                                                      ^

TypeError: Cannot read property '1' of null
    at Object.exports.getGeneralInfo (/Users/adityagupta/Desktop/DashBot/node_modules/ytpl/lib/util.js:27:71)
    at IncomingMessage.<anonymous> (/Users/adityagupta/Desktop/DashBot/node_modules/ytpl/lib/firstpage.js:30:29)
    at IncomingMessage.emit (node:events:388:22)
    at endReadableNT (node:internal/streams/readable:1295:12)
```

**Comment by TimeForANinja** [comment]
you must be running a very very very very old version
update 😉

**Comment by aditya-learns** [comment]
i just downloaded it today

**Comment by TimeForANinja** [comment]
then you might wanna try `npm ls ytpl` to list all installed ytpl-instanzes
latest version is v2.0.0

**Comment by aditya-learns** [comment]
i did that command, my version says 2.0.1

**Comment by TimeForANinja** [comment]
sounds more like an npm problem
the file that produced the error does not exists in the v2.0.1
so my suggestions:
* wipe the whole `node_modules` folder
* remove any `package-lock.json`
* reinstall npm

**Comment by aditya-learns** [comment]
The error was with the version. My version was 2.0.1 but the bot worked with 2.0.0

**Comment by TimeForANinja** [comment]
again
that error can't come from v2.0.1 or v2.0.0
looks like an npm or configuration problem to me

so as adviced before: redo your dependencies
check if the module you require is the one that showed when you did `npm ls`
try `npm uninstall ytpl` and see if your program still runs and finds another ytpl that's causing problems

**Comment by aditya-learns** [comment]
I deleted ytpl and installed it in 2.0.0 and it worked
