### ISSUE TITLE
The playlist description is not available 

### ISSUE THREAD

**Issue by Asgarrrr** [TimeForANinja/node-ytpl#113]
The description of the playlist is always equal to `null`. 

I took a [random playlist](https://www.youtube.com/playlist?list=PLw-VjHDlEOgv3mwL0SHhMEpNBl8mq2kp4) that has a description, and ... : 

<img width="305" alt="Capture d’écran 2021-05-04 à 11 37 58" src="https://user-images.githubusercontent.com/36574651/116985736-2e4cf280-accd-11eb-9196-2ddd762c3428.png">

I can't say if it's always the case, but on all the playlists I tested, the description is missing.

Thank you ;3

**Comment by TimeForANinja** [comment]
🤔 can replicate - will have a look

**Comment by Asgarrrr** [comment]
Good luck ! ;3

**Comment by Asgarrrr** [comment]
I made a little motification, which solves the problem  #114

**Comment by TimeForANinja** [comment]
closed with #114
