### ISSUE TITLE
Chapters support

### ISSUE THREAD

**Issue by Hydro001** [TimeForANinja/node-ytpl#130]
Hi, would it be possible to add chapters support for ytpl ?
If there isn't any chapters, just return an empty array for exemple.

Have a nice day.

**Comment by TimeForANinja** [comment]
as far as i know chapters are a video feature and not displayed in playlists - that would mean it's not feasible

**Comment by Hydro001** [comment]
Oh, does that mean that i have to do something like an ytdl.get_basic_info to know if the videos contains some ?

**Comment by TimeForANinja** [comment]
Yep, as far as i know you'd have to fetch each individual video
There are a few ways you can stretch ratelimits - check the ytdl-core readme for more on that

**Comment by Hydro001** [comment]
Thanks for the help, i will look at what you said, have a nice day.
