### ISSUE TITLE
Can't handle playlist created by YT

### ISSUE THREAD

**Issue by DanielBUBU** [TimeForANinja/node-ytpl#132]
If you use the link, YT will create a unique playlist according the song and the account you logged in
https://www.youtube.com/watch?v=IvaaRFvwzgc&list=RDMMIvaaRFvwzgc

Is there any method to fetch this list?

**Comment by TimeForANinja** [comment]
those are called mixes
they are not supported and i don't see adding it in the future
a few problem with them are:
* they are infinite length => could result in infinitely pulling videos
* they are not simple playlists but depend on a video => video is removed when resolving playlist id
* there is no playlist page (they are part of the video page) => that page is never pulled

i could however see this as a feature of ytdl-core (similar to the related videos)

**Comment by DanielBUBU** [comment]
> those are called mixes they are not supported and i don't see adding it in the future a few problem with them are:
> 
> * they are infinite length => could result in infinitely pulling videos
> * they are not simple playlists but depend on a video => video is removed when resolving playlist id
> * there is no playlist page (they are part of the video page) => that page is never pulled
> 
> i could however see this as a feature of ytdl-core (similar to the related videos)

ytdl-core has provided the function to find the related videos?How?
I haven't seen that in readme before
