### ISSUE TITLE
Add support for the new YouTube channel handles

### ISSUE THREAD

**Issue by ahm750** [TimeForANinja/node-ytpl#147]
This package doesn't seem to support the new channel handles introduced by YouTube in October 2022.

Here's an example of the new handles: https://www.youtube.com/@MrBeast

When I try this URL with ytpl, it throws the following error: Unable to find a id in "https://www.youtube.com/@MrBeast"

Any chance that this new URL format can be supported?

**Comment by zeeshanakram3** [comment]
Any updates on this?

@ahm750 did you find any alternative? Thanks

**Comment by YLS-** [comment]
It would be great to get support for these new handles.

If you only know a channel's new handle like [@MrBeast](https://www.youtube.com/@MrBeast), it is not obvious how to extract the underlying channel ID and pass it as input to `ytpl()`.
