### ISSUE TITLE
Support proxy same as in node-ytdl-core

### ISSUE THREAD

**Issue by Murena7** [TimeForANinja/node-ytpl#35]
Hi, can you please implement support proxy functionality, same as in node-ytdl-core. Thanks!

**Comment by TimeForANinja** [comment]
👍 done with rework & the switch to miniget

**Comment by chrisr11** [comment]
> 👍 done with rework & the switch to miniget

Can you add an example to show how it can be used? I did it like ytdl-core where an HttpsProxyAgent is passed as an option to ytpl, but it doesn't work.

**Comment by Murena7** [comment]
> 👍 done with rework & the switch to miniget

miniget don't work with proxy - can you please show some example ?
