### ISSUE TITLE
Add Other Video Thumbnails to Items List

### ISSUE THREAD

**Issue by PrestonN** [TimeForANinja/node-ytpl#37]
Hello!

It would be nice if this module could include an array of the other video thumbnail qualities that are available for the items within a playlist  Specifically I'd like to use the thumbnails provided by YouTube that don't have the black bars surrounding the thumbnail.

Thank you!

**Comment by TimeForANinja** [comment]
I'm not sure whether they are provided via unofficial ways.
If i remember right, there has been a long discussion on https://github.com/fent/node-ytdl-core/ about thumbnail url's and how they are simply build using schemes like `https://img.youtube.com/vi/${videoID}/maxresdefault.jpg` which make them basicly unable to validate without requesting...
Or did i missunderstand your question?

**Comment by PrestonN** [comment]
Ahh, I see.  In that case that should be good enough for my need.  I'll just do that instead.  Thanks for the reply!
