### ISSUE TITLE
Error: We'll stop supporting this browser soon.

### ISSUE THREAD

**Issue by chowdapowa9** [TimeForANinja/node-ytpl#38]
Whenever I use YTPL to grab a playlist from YouTube, I get this error message.

```
Error: We’ll stop supporting this browser soon. For the best experience please <a href="/supported_browsers">update your browser</a>.
    at IncomingMessage.resp.on (/home/pi/.djsbots/Nookbot/node_modules/ytpl/lib/firstpage.js:26:49)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by skdev24** [comment]
Yes, because of `disable_polymer=true`, @TimeForANinja?

**Comment by naugtur** [comment]
Same here. 
How can I help?

**Comment by GreepTheSheep** [comment]
Same.

**Comment by naugtur** [comment]
Would faking a useragent be enough, or is it more advanced than that?

**Comment by TimeForANinja** [comment]
#40 seems to fix the Problem for me
you guys could give it a try using `npm i NotArandomGUY/node-ytpl#master` and inform me, whether that worked for you - even thou there's a high chance that just adding a host may only delay problems...
Will take me a bit longer this time to adjust & incorporate the changes

**Comment by naugtur** [comment]
Until they switch to JavaScript only, passing the useragent header will suffice. 
I'll test it as soon as I'm at a keyboard.

**Comment by Block2Block** [comment]
@TimeForANinja it works for me :)

**Comment by GreepTheSheep** [comment]
Working for me too 👍

**Comment by naugtur** [comment]
Using it just fine.

**Comment by chowdapowa9** [comment]
Works great! Thanks for the quick patch!

**Comment by bhushankumarl** [comment]
@chowdapowa9 
Can you release it in a new version?

**Comment by chowdapowa9** [comment]
I don't manage this repository. There's already a pull request for it. #40

**Comment by Bluebie** [comment]
This version works well for me. Code quality looks reasonable even if commit messages leave something to be desired. The change is very minimal, unlikely to create new problems. Worthy of a merge, i think!
