### ISSUE TITLE
Cannot send requests?

### ISSUE THREAD

**Issue by alex-taxiera** [TimeForANinja/node-ytpl#4]
Just started to try out this module, but I cannot even get the example code to run proper?

I am getting a TypeError "Cannot read property 'splice' of null at ytpl\lib\firstpage.js:20:50

Thought it was just me so I tried runkit and same thing? 
https://runkit.com/593239ab2a105b001274636c/593246e004544700129567cf

edit: in order to get around this for NOW, I just put ```if (resp_string.match(error_regexp_g) !== null)``` before trying to splice and find any errors.

**Comment by TimeForANinja** [comment]
hmmm, still works for me...
can u do me a favour and send me a dumb of `https://www.youtube.com/playlist?list=UU_aEa8K-EOJ3D6gOs7HcyNg` taken via node?
just copy the file content of this into a hastebin or sth like that
```js
    var https = require('https');
    https.get('https://www.youtube.com/playlist?list=UU_aEa8K-EOJ3D6gOs7HcyNg', resp => resp.pipe(fs.createWriteStream('dumb.html')))
```

**Comment by alex-taxiera** [comment]
File contents was too large for hastebin
[dumb.txt](https://github.com/TimeForANinja/node-ytpl/files/1049695/dumb.txt)

**Comment by TimeForANinja** [comment]
Thanks for telling me
If i understood it right the problem was that since my location's native language is not english, it always showed a `choose ur language` error

**Comment by alex-taxiera** [comment]
perfect, completely fixed that issue for me!
