### ISSUE TITLE
TypeScript support for the helper functions

### ISSUE THREAD

**Issue by cfanoulis** [TimeForANinja/node-ytpl#45]
Hello! I've realized you have typings only for the main ytpl functions. Is there any possibility you'll add the other functions (`getPlaylistID` and `validateURL`) in the typings? Thanks

**Comment by TimeForANinja** [comment]
I'd love to but unfortunately they we're gifted and i'm not good with typescript 😅

**Comment by cfanoulis** [comment]
Alright... I'll see if I can make them myself

**Comment by TimeForANinja** [comment]
done with #53
