### ISSUE TITLE
Inconsistent options behaviour: {} is not the same as no options object

### ISSUE THREAD

**Issue by trustedtomato** [TimeForANinja/node-ytpl#5]
I think it's because they replaced the load more button with infinite scroll.

**Comment by TimeForANinja** [comment]
This package shouldn't be able to parse items from the new layout at all, since they are saved differently now
i guess its the default limit of 100 stopping it of pulling more so try to pass an empty object `{}` as second parameter

**Comment by trustedtomato** [comment]
Hmmm, fine, it works with that, but that default limit is pretty unexpected.

**Comment by TimeForANinja** [comment]
resolved with https://github.com/TimeForANinja/node-ytpl/commit/581666586c2a62efe82d8819606be59e5942d587

**Comment by TimeForANinja** [comment]
thanks for letting me know about that problem
