### ISSUE TITLE
Album id as argument

### ISSUE THREAD

**Issue by corwin-of-amber** [TimeForANinja/node-ytpl#56]
Any reason why `ytpl(id)` can accept a plain list ID (`PLAYLIST_REGEX`) but not an album ID (`ALBUM_REGEX`)?

e.g. `ytpl('?list=OLAK5uy_kAVbBOLaBZPmxyy3OP0aEAwA-87MgV004')` works, but `ytpl('OLAK5uy_kAVbBOLaBZPmxyy3OP0aEAwA-87MgV004')` throws:
```
Error: Unable to find a id in OLAK5uy_kAVbBOLaBZPmxyy3OP0aEAwA-87MgV004
```

**Comment by TimeForANinja** [comment]
just not implemented 😉

**Comment by corwin-of-amber** [comment]
Thanks for the reply! It seems like the fix is tiny, I wondered if there's something deeper that I didn't catch. Namely the line:
https://github.com/TimeForANinja/node-ytpl/blob/3a864ded1f83e5c142d7c4328e716de60fa4b03d/lib/main.js#L61
should be made to look more like the condition in 
https://github.com/TimeForANinja/node-ytpl/blob/3a864ded1f83e5c142d7c4328e716de60fa4b03d/lib/main.js#L65

**Comment by TimeForANinja** [comment]
yep, that would already do the trick

**Comment by corwin-of-amber** [comment]
Yay!
