### ISSUE TITLE
Any link doesn't work

### ISSUE THREAD

**Issue by brunogomes98** [TimeForANinja/node-ytpl#60]
title: exports.removeHtml(importantTxt.match(PLAYLIST_NAME_REGEXP)[1]),
                                                                      ^

TypeError: Cannot read property '1' of null

https://imgur.com/QyTZjws

**Comment by Thorsieger** [comment]
Same issues as #58

**Comment by naugtur** [comment]
Confirmed. Seeing the same.
Looks like youtube changed their markup in the playlist pages.

**Comment by Eomm** [comment]
For me locking the dep to `0.1.21` works

Ref https://github.com/Eomm/youtube-download-playlist/issues/7
