### ISSUE TITLE
Only getting first 100 videos of a playlist

### ISSUE THREAD

**Issue by PhoenixOnARoof** [TimeForANinja/node-ytpl#71]
I am using the module to get playlist info for music commands in my discord bot. The module will only return the first 100 items of a playlist. I've tried multiple playlists of varying sizes over 100 but the result is always the same. I've used the latest available npm version and the rework branch version. 

In the case of the npm version I'm using `limit=0` and with the rework branch version im using `limit=Infinity`. If I use it the way it's written in the documentation `limit[Number]` it just results in `ReferenceError: limit is not defined` So what am I doing wrong? 🥴

**Comment by TimeForANinja** [comment]
🤔 still works for me
the `limit[Number]` basically tells you the type of the argument
in the end your call should look sth like this:
```js
require('ytpl')('UU_aEa8K-EOJ3D6gOs7HcyNg', {limit: Infinity}).then(i => console.log(i.items.length))
```

**Comment by PhoenixOnARoof** [comment]
> 🤔 still works for me
> the `limit[Number]` basically tells you the type of the argument
> in the end your call should look sth like this:
> 
> ```js
> require('ytpl')('UU_aEa8K-EOJ3D6gOs7HcyNg', {limit: Infinity}).then(i => console.log(i.items.length))
> ```
> 
> does this work for you?

This is exactly why I shouldn't be writing code in the middle of the night 🤦 🤦‍♂️ 
I did not realize that I needed to surround the limit in `{}` at the time. It works as it should with that. Sorry 🥴

**Comment by TimeForANinja** [comment]
np 😉

**Comment by Nico-ITA** [comment]
Guys for me this dont work ;(

**Comment by TimeForANinja** [comment]
@Nico-ITA pls open a new Issue
a) add how you use the library
b) add what you expect to happen
c) add what does happens
