### ISSUE TITLE
Cannot read property 'split' of null

### ISSUE THREAD

**Issue by SwanX1** [TimeForANinja/node-ytpl#74]
```
Function.main.validateURL (C:\Users\Karlis\Desktop\co\node\receptionist\node_modules\ytpl\lib\main.js:94:29)
```
The `TypeError: Cannot read property 'split' of null` occurs when argument `link` of `main.validateURL` is an empty string or whitespace, since the property `pathname` will always be null when such circumstances occur. 
Can be solved outside the package checking if `parsed.pathname === null` beforehand, however it is good practice to do that in the package too.

**Comment by TimeForANinja** [comment]
added in https://github.com/TimeForANinja/node-ytpl/commit/a0ea805ae763e4b0014a382e706f5893c9a38fc1
also added tests so it doesn't happen again
👍
