### ISSUE TITLE
Error: Some playlist features are going away soon.

### ISSUE THREAD

**Issue by maxill1** [TimeForANinja/node-ytpl#77]
invoking ytpl on any playlist gives this result:

**Some playlist features are going away soon. <a href="//support.google.com/youtube/answer/9072033">Learn more</a>**

used default snippet:
```
var ytpl = require('ytpl');

ytpl('UU_aEa8K-EOJ3D6gOs7HcyNg').then(playlist => {
  dosth(playlist);
}).catch(err => {
  console.error(err);
});
```

**Comment by zaidabldllah** [comment]
i have same issues

**Comment by TimeForANinja** [comment]
fixed with https://github.com/TimeForANinja/node-ytpl/commit/1fb5f5e1acdbfe513ade05fd29ef07d924a2dba0
