### ISSUE TITLE
Support YouTube Music Playlist

### ISSUE THREAD

**Issue by skick1234** [TimeForANinja/node-ytpl#80]
Support YouTube Music playlist or at least remove it from the regular expressions.
YouTube Music is not available in my country so I haven't tried parsing it but I think it is similar to a YouTube playlist.

**Comment by TimeForANinja** [comment]
do you mean playlists starting with `RD`?

**Comment by skick1234** [comment]
> do you mean playlists starting with `RD`?

No, it's mixes.
I mean music.youtube.com playlist.

**Comment by skick1234** [comment]
> do you mean playlists starting with `RD`?

This link caused Unknown error in my console: https://music.youtube.com/playlist?list=OLAK5uy_lOSSulPhlDoz7l0kUBB83z8As79NS6GkA

**Comment by TimeForANinja** [comment]
🤔 works on my machine

**Comment by skick1234** [comment]
```
Error: Unknown error.
at module.exports (/home/container/node_modules/ytpl/lib/firstpage.js:24:35)
```
I tried many times but it doesn't work 2 days ago. But it seems to be fine now. Maybe network issues or YouTube responded to something weird?

**Comment by TimeForANinja** [comment]
feel free to reopen if this happens again 🤔
