### ISSUE TITLE
Is not Working!!!!

### ISSUE THREAD

**Issue by kabeer11000** [TimeForANinja/node-ytpl#86]

**Comment by dbrn** [comment]
There are some problems with the new data format that Youtube is returning.
Please check this other thread: #85 
Thank you.

**Comment by mirsella** [comment]
@kabeer11000 thanks for reporting a issue, but please check before if there is already one open for this error.

**Comment by TimeForANinja** [comment]
yep, closed as duplicate

**Comment by kabeer11000** [comment]
thanks man i appreciate you guys maintain these youtube scrapers.
