### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by muhimur9049** [TimeForANinja/node-ytpl#91]
![image](https://user-images.githubusercontent.com/52611945/100308835-53e40c00-2f77-11eb-95d8-6e096591e4c8.png)

I am getting this strange error for YT playlists. The file looks like this (latest version) https://srcb.in/6kUEGWqTcN

**Comment by TimeForANinja** [comment]
🤔 with ytsr they sometimes ended the json with different combinations of spaces and semicolons
try switching to a newer version of the #wip-api-adjustments branch
changed the way the json is pulled there

**Comment by muhimur9049** [comment]
How can I install it with npm? I tried reinstalling ytpl but didn’t work.

**Comment by TimeForANinja** [comment]
Try `npm I ytpl@wip`
