### ISSUE TITLE
Chance of encountering HTTP error 429?

### ISSUE THREAD

**Issue by patrickkfkan** [TimeForANinja/node-ytpl#95]
Hello,

Looking at your code, it seems that results are fetched in iterations until limit is reached. To my knowledge, YouTube checks for bot-like requests and responds with HTTP error 429 if too many requests are made within a short period. I recently encountered this while playing with various YouTube scraping libraries and my IP address got 429ed by Google :( ...had to wait a couple of hours for Google to unblock me.

In your experience, what is the chance of getting 429ed if I set a limit of, say, 500? Would it make a difference if a slight delay (say 1-2 seconds) is added before each request?

The same goes for your ytsr library ;)

Regards,
Patrick

**Comment by TimeForANinja** [comment]
regular usage shouldn't get you rate limited
i managed to fetch playlists of 20k videos without issues
you really have to spam to get banned

it should be possible thou to do the same ipv6 rotation ytdl-core is planning to add

**Comment by patrickkfkan** [comment]
Thanks for the clarification!
