### ISSUE TITLE
(wip) Error: continueReq only allowed for paged requests

### ISSUE THREAD

**Issue by patrickkfkan** [TimeForANinja/node-ytpl#97]
Hello,

Just did a bit of testing with the wip branch (sorry, couldn't wait).. I got an error with `continueReq()`:

> Error: continueReq only allowed for paged requests

I just fed the `continuation` object returned by ytpl to `continueReq()`, like the example in the Readme.

Looking at the line that throws this error:

> if (!isNaN(args[3].limit)) throw new Error('continueReq only allowed for paged requests');

But then, `args[3].limit` (i.e. `opts.limit`) is always Infinity when `continuation` is returned. That means `!isNaN(args[3].limit)` will always be true (hence the error)?

I haven't tested ytsr yet, but glancing at the code I suppose it's going to be the same ;) ?

Thanks,
Patrick

**Comment by TimeForANinja** [comment]
nice spotting
i'm happy with every error found before i merge to master 👍🏻 
fix on it's way

**Comment by TimeForANinja** [comment]
fixed in https://github.com/TimeForANinja/node-ytpl/commit/55697d56d2c94336b16ec90c016e8270ed845e2a
