### ISSUE TITLE
(wip) TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by patrickkfkan** [TimeForANinja/node-ytpl#98]
Hello,

I have found that, for some playlists, such as [this one](https://www.youtube.com/playlist?list=PLGzC4gTcebz_DtErBUKNdZZdPwkb5e-pr), ytpl fails when trying to parse the description text. 

Dumping the playlist info to console shows this:

> { thumbnailRenderer: { playlistVideoThumbnailRenderer: { thumbnail: [Object] } },
  title: { runs: [ [Object] ] },
  stats: 
   [ { runs: [Array] },
     { simpleText: '4,413 views' },
     { runs: [Array] } ],
  menu: 
   { menuRenderer: 
      { items: [Array],
        trackingParams: 'CAEQk-8CIhMIqNmJ-azG7QIVBQZgCh1XKgeS',
        topLevelButtons: [Array],
        accessibility: [Object] } },
  thumbnailOverlays: [ { thumbnailOverlaySidePanelRenderer: [Object] } ],
  navigationEndpoint: 
   { clickTrackingParams: 'CAEQk-8CIhMIqNmJ-azG7QIVBQZgCh1XKgeSWiRWTFBMR3pDNGdUY2Viel9EdEVyQlVLTmRaWmRQd2tiNWUtcHKaAQMQ-iw=',
     commandMetadata: { webCommandMetadata: [Object] },
     watchEndpoint: 
      { videoId: 'HvJ21S5qEjQ',
        playlistId: 'PLGzC4gTcebz_DtErBUKNdZZdPwkb5e-pr' } },
  description: {},
  showMoreText: { runs: [ [Object] ] } }
...

Instead of null, the description field is an empty object, so parseText() in utils fails to get the 'simpleText' or 'runs' property from it.

I am able to bypass the error by changing the following line in `utils.js` from:

>const parseText = exports.parseText = txt => txt.simpleText || txt.runs.map(a => a.text).join('');

to this:

>const parseText = exports.parseText = txt => txt.simpleText || (txt.runs ? txt.runs.map(a => a.text).join('') : null);

I'm not sure if this is the correct way to this, though. 

Btw, is it fine with you to raise issues on the wip branch since I know you're still working on it? I just thought it might be more appropriate to point out issues as I find them, rather than seeing them committed to the master branch.

-Patrick

**Comment by TimeForANinja** [comment]
one of those errors where i feel like youtube has some errors in there api...
👍🏻 keep em coming
fixed in https://github.com/TimeForANinja/node-ytpl/commit/b31cdb986bfe56f6334d253b735115f448654929
